version: "3.8"
services:
  analytics-service:
    build: ./analytics-service
    ports:
      - "9095:9090"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SERVER_PORT=8081
    networks:
      - microservices-net

  simple-notification-service:
    build: ./simple-notification-service
    ports:
      - "8087:8087"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SERVER_PORT=8083
    networks:
      - microservices-net

  audit-service:
    build: ./audit-service
    ports:
      - "8089:8089"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SERVER_PORT=8082
    networks:
      - microservices-net

  games-swap-service:
    build: ./games-swap-service
    ports:
      - "8079:8079"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - GRPC_CLIENT_ANALYTICS_SERVICE_ADDRESS=static://analytics-service:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://my-postgres:5432/mydb
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - microservices-net

networks:
  microservices-net:
    external: true