global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "sop"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          [
            "games-swap-service:8080",
            "simple-notification-service:8083",
            "audit-service:8082",
            "analytics-service:8081",
          ]
